languageCode = "en"
languageName = "English"
weight = 1
title = "Blog Adrià"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "assets"
copyright = "&copy: 2024 Adrià Lisa. All Rights Reserved."

[author]
name = "Adrià Lisa"
image = "adrimochi.jpg"
headline = "Avid generalist"
bio = "I am an IT enthusiast, although my background is in mathematics. I currently work as a data engineer/scientitst at Zenement."
links = [ { email = "adrialisa99@gmail.com" } ]
