languageCode = "en"
languageName = "English"
weight = 1
title = "Blog Adrià"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "assets"

[author]
name = "Adrià Lisa"
image = "assets"
headline = "Avid generalist"
