

[[main]]
name = "Sobre mi"
pre = "circle-info"
pageRef = "about"
identifier = "AytD2x5sF3"
weight = 9999

[[main]]
name = "CV"
pre = "download"
pageRef = "cv"
identifier = "rohyXfYqIS"
weight = 9999

[[main]]
name = "Diario de programador"
pre = "code"
pageRef = "diary"
identifier = "ipFhpPbHeH"
weight = 9999

[[footer]]
none = "none"
