[[main]]
none = "none"

[[main]]
name = "About"
pre = "circle-info"
pageRef = "about"
identifier = "AytD2x5sF3"
weight = 9999

[[main]]
name = "CV"
pre = "download"
pageRef = "cv"
identifier = "rohyXfYqIS"
weight = 9999

[[main]]
name = "Dev diary"
pre = "code"
pageRef = "diary"
identifier = "ipFhpPbHeH"
weight = 9999

[[footer]]
pre = "github"
url = "https://github.com/AdriaCoding"
identifier = "DyeHjjyoHb"
weight = 9999

[[footer]]
pre = "linkedin"
url = "https://www.linkedin.com/in/adri%C3%A0-lisa/"
identifier = "C92jLReU0B"
weight = 9999
